# Generated by Django 4.1.2 on 2023-03-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
