# Generated by Django 4.1.7 on 2023-03-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_like_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
    ]
